System.ArgumentException: An item with the same key has already been added (#140)
* Adding try catch to when adding mapping values to dictonary. If duplicate is found catch exception, log it and continue.